### Uncomment the custom rules section below to:
### - pull preferentially from the ingest results.
### See README.md for more information

#custom_rules:
#    - build-configs/state_focused/copy_from_ingest.smk
builds: 'genome'
custom_subsample:
    genome:
        defaults:
            exclude_ambiguous_dates_by: year  
        samples:
            state:
                query: division == "Washington"
                max_sequences: 2000
                min_length: 5000
                min_date: "1950"
                exclude:
                    - defaults/dropped_strains.txt
            continental:
                query: division != "Washington" & region == "North America"
                max_sequences: 2000
                min_length: 5000
                min_date: "1950"
                exclude:
                    - defaults/dropped_strains.txt
            global:
                query: region != "North America"
                max_sequences: 2000
                min_length: 5000
                min_date: "1950"
                include:
                    - defaults/include_strains_genome.txt
                exclude:
                    - defaults/dropped_strains.txt