# This configuration file should contain all required configuration parameters
# for the ingest workflow to run to completion.
#
# Define optional config parameters with their default values here so that users
# do not have to dig through the workflows to figure out the default values


# Required to fetch from NCBI Datasets
ncbi_taxon_id: "11234"

ppx_fetch:
  seqs: https://lapis.pathoplexus.org/measles/sample/unalignedNucleotideSequences?versionStatus=LATEST_VERSION
  meta: https://lapis.pathoplexus.org/measles/sample/details?dataFormat=csv&versionStatus=LATEST_VERSION

# The list of NCBI Datasets fields to include from NCBI Datasets output
# These need to be the mneumonics of the NCBI Datasets fields, see docs for full list of fields
# https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/command-line/dataformat/tsv/dataformat_tsv_virus-genome/#fields
# Note: the "accession" field MUST be provided to match with the sequences
ncbi_datasets_fields:
  - accession
  - sourcedb
  - sra-accs
  - isolate-lineage
  - geo-region
  - geo-location
  - isolate-collection-date
  - release-date
  - update-date
  - length
  - genotype
  - host-name
  - isolate-lineage-source
  - biosample-acc
  - submitter-names
  - submitter-affiliation
  - submitter-country
  - virus-name

# Config parameters related to the curate pipeline
curate:
  # The path to the local geolocation rules for this pathogen.
  # The path should be relative to the working directory (e.g. --directory).
  # If the path doesn't exist in the working directory, the file in the workflow's defaults/ directory it used instead (if it exists).
  local_geolocation_rules: "geolocation_rules.tsv"
  # List of field names to change where the key is the original field name and the value is the new field name
  # The original field names should match the ncbi_datasets_fields provided above.
  # This is the first step in the pipeline, so any references to field names in the configs below should use the new field names
  field_map:
    accession: accession
    accession_version: accession_version
    sourcedb: database
    sra-accs: sra_accessions
    isolate-lineage: strain
    geo-region: region
    geo-location: location
    isolate-collection-date: date
    release-date: date_released
    update-date: date_updated
    length: length
    host-name: host
    isolate-lineage-source: sample_type
    biosample-acc: biosample_accessions
    submitter-names: authors
    submitter-affiliation: institution
    submitter-country: submitter_country
    virus-name: virus_name
    is_reference: is_reference
  ppx_field_map:
    sampleCollectionDate: date
    displayName: strain
    earliestReleaseDate: date_submitted
    accessionVersion: PPX_accession
    insdcAccessionFull: INSDC_accession
    ncbiVirusName: virus_name
    geoLocCountry: country
    geoLocAdmin1: division
    geoLocAdmin2: location
    genotype: genotype_ppx
    hostNameCommon: host
    insdcRawReadsAccession: sra_accession
    dataUseTermsRestrictedUntil: restrictedUntil
    dataUseTermsUrl: dataUseTerms__url
    authorAffiliations: institution
  # Standardized strain name regex
  # Currently accepts any characters because we do not have a clear standard for strain names across pathogens
  strain_regex: '^.+$'
  # Back up strain name field to use if 'strain' doesn't match regex above
  strain_backup_fields: []
  # List of date fields to standardize to ISO format YYYY-MM-DD
  date_fields: ['date', 'date_submitted']
  # List of expected date formats that are present in the date fields provided above
  # These date formats should use directives expected by datetime
  # See https://docs.python.org/3.9/library/datetime.html#strftime-and-strptime-format-codes
  expected_date_formats: ['%Y', '%Y-%m', '%Y-%m-%d', '%Y-%m-%dT%H:%M:%SZ']
  # The expected field that contains the GenBank geo_loc_name
  genbank_location_field: location
  titlecase:
    # List of string fields to titlecase
    fields: ['region', 'country', 'division', 'location']
    # List of abbreviations not cast to titlecase, keeps uppercase
    abbreviations: ['USA']
    # Articles that should not be cast to titlecase
    articles: [
      'and', 'd', 'de', 'del', 'des', 'di', 'do', 'en', 'l', 'la', 'las', 'le',
      'los', 'nad', 'of', 'op', 'sur', 'the', 'y'
    ]
  # Metadata field that contains the list of authors associated with the sequence
  authors_field: "authors"
  # Default value to use if the authors field is empty
  authors_default_value: "?"
  # Name to use for the generated abbreviated authors field
  abbr_authors_field: "abbr_authors"
  # Path to the manual annotations file
  # The path should be relative to the working directory (e.g. --directory).
  # If the path doesn't exist in the working directory, the file in the workflow's defaults/ directory it used instead (if it exists).
  annotations: "annotations.tsv"
  # The ID field in the metadata to use to merge the manual annotations
  annotations_id: "accession"
  # The ID field in the metadata to use as the sequence id in the output FASTA file
  output_id_field: "accession"
  # The field in the NDJSON record that contains the actual genomic sequence
  output_sequence_field: "sequence"
  # The list of metadata columns to keep in the final output of the curation pipeline.
  metadata_columns: [
    'accession',
    'accession_version',
    'strain',
    'virus_name',
    'date',
    'region',
    'country',
    'division',
    'location',
    'length',
    'host',
    'date_released',
    'date_updated',
    'sra_accessions',
    'authors',
    'abbr_authors',
    'institution',
    'is_reference'
  ]
  genotype_field: "virus_name"
  ppx_metadata_columns: [
    'strain',
    'date',
    'accession', # unversioned PPX accession
    'PPX_accession',
    'PPX_accession__url',
    'INSDC_accession',
    'INSDC_accession__url',
    'region',
    'country',
    'division',
    'location',
    'host',
    'date_submitted',
    'sra_accession',
    'authors',
    'institution',
    'dataUseTerms',
    'dataUseTerms__url',
    'restrictedUntil',
  ]
nextclade:
  dataset_name: "nextstrain/measles/N450/WHO-2012"
  field_map:
    # The first column should be the original column name of the Nextclade TSV
    # The second column should be the new column name to use in the final metadata TSV
    # Nextclade can have pathogen specific output columns so make sure to check which
    # columns would be useful for your downstream phylogenetic analysis.
    seqName: seqName
    clade: clade
    coverage: coverage
    totalMissing: missing_data
    totalSubstitutions: divergence
    totalNonACGTNs: nonACGTN
    qc.overallStatus: QC_overall
    qc.missingData.status: QC_missing_data
    qc.mixedSites.status: QC_mixed_sites
    qc.privateMutations.status: QC_rare_mutations
    qc.snpClusters.status: QC_snp_clusters
    qc.frameShifts.status: QC_frame_shifts
    qc.stopCodons.status: QC_stop_codons
    frameShifts: frame_shifts
    privateNucMutations.reversionSubstitutions: private_reversion_substitutions
    privateNucMutations.labeledSubstitutions: private_labeled_substitutions
    privateNucMutations.unlabeledSubstitutions: private_unlabeled_substitutions
    privateNucMutations.totalReversionSubstitutions: private_total_reversion_substitutions
    privateNucMutations.totalLabeledSubstitutions: private_total_labeled_substitutions
    privateNucMutations.totalUnlabeledSubstitutions: private_total_unlabeled_substitutions
    privateNucMutations.totalPrivateSubstitutions: private_total_private_substitutions
    qc.snpClusters.clusteredSNPs: private_snp_clusters
    qc.snpClusters.totalSNPs: private_total_snp_clusters
  id_field: "seqName"

ppx_metadata_fields: # Used to create the URL to download PPX metadata
 - "accessionVersion"
 - "accession"
 - "version"
 - "submitter"
 - "groupName"
 - "submittedDate"
 - "releasedDate"
 - "dataUseTerms"
 - "dataUseTermsRestrictedUntil"
 - "dataUseTermsUrl"
 - "assemblyReferenceGenomeAccession"
 - "authorAffiliations"
 - "authors"
 - "bioprojectAccession"
 - "biosampleAccession"
 - "completeness"
 - "displayName"
 - "earliestReleaseDate"
 - "frameShifts"
 - "geoLocAdmin1"
 - "geoLocAdmin2"
 - "geoLocCity"
 - "geoLocCountry"
 - "geoLocLatitude"
 - "geoLocLongitude"
 - "geoLocSite"
 - "hostAge"
 - "hostAgeBin"
 - "hostDisease"
 - "hostGender"
 - "hostHealthOutcome"
 - "hostHealthState"
 - "hostNameCommon"
 - "hostOriginCountry"
 - "hostVaccinationStatus"
 - "insdcAccessionBase"
 - "insdcAccessionFull"
 - "insdcRawReadsAccession"
 - "insdcVersion"
 - "isLabHost"
 - "length"
 - "ncbiReleaseDate"
 - "ncbiSourceDb"
 - "ncbiSubmitterCountry"
 - "ncbiUpdateDate"
 - "ncbiVirusName"
 - "ncbiVirusTaxId"
 - "purposeOfSampling"
 - "purposeOfSequencing"
 - "qualityControlDetails"
 - "qualityControlDetermination"
 - "qualityControlIssues"
 - "qualityControlMethodName"
 - "qualityControlMethodVersion"
 - "sampleCollectionDate"
 - "sampleCollectionDateRangeLower"
 - "sampleCollectionDateRangeUpper"
 - "sampleType"
 - "totalAmbiguousNucs"
 - "totalDeletedNucs"
 - "totalFrameShifts"
 - "totalInsertedNucs"
 - "totalSnps"
 - "totalUnknownNucs"
 - "travelHistory"
