# NOTE: These files contain restricted sequences. If you are using these in
# your own analysis, please refer to the Pathoplexus Data Use Terms.
# <https://pathoplexus.org/about/terms-of-use/restricted-data>
additional_inputs:
  - name: ppx_restricted
    metadata: "s3://nextstrain-data/files/workflows/measles/metadata_restricted.tsv.zst"
    sequences: "s3://nextstrain-data/files/workflows/measles/sequences_restricted.fasta.zst"

custom_rules:
  - build-configs/nextstrain-automation/deploy.smk

deploy_url: "s3://nextstrain-data"
